// Code generated by "stringer -type=ArgType"; DO NOT EDIT.

package goargs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeString-0]
	_ = x[TypeBool-1]
}

const _ArgType_name = "TypeStringTypeBool"

var _ArgType_index = [...]uint8{0, 10, 18}

func (i ArgType) String() string {
	if i >= ArgType(len(_ArgType_index)-1) {
		return "ArgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArgType_name[_ArgType_index[i]:_ArgType_index[i+1]]
}
