// Code generated by "stringer -type=SourceType"; DO NOT EDIT.

package goargs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceNotFound-0]
	_ = x[SourceFile-1]
	_ = x[SourceEnv-2]
	_ = x[SourceArgs-3]
}

const _SourceType_name = "SourceNotFoundSourceFileSourceEnvSourceArgs"

var _SourceType_index = [...]uint8{0, 14, 24, 33, 43}

func (i SourceType) String() string {
	if i >= SourceType(len(_SourceType_index)-1) {
		return "SourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SourceType_name[_SourceType_index[i]:_SourceType_index[i+1]]
}
